/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jarc.apk;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JToggleButton;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.erdfelt.android.apk.AndroidApk;

/**
 * UI of JARC-APK
 * @author Paul Alves
 */
public class JARCUI extends javax.swing.JFrame {

    /**
     * Creates new form JARCUI
     */
    public JARCUI() {
        initComponents();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildTarget = new javax.swing.ButtonGroup();
        slotBG = new javax.swing.ButtonGroup();
        orientationGroup = new javax.swing.ButtonGroup();
        errorDia = new javax.swing.JDialog();
        okError = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        writeDir = new javax.swing.JFileChooser();
        readAPK = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chromeOSBuild = new javax.swing.JRadioButton();
        archonBuild = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pkgName = new javax.swing.JTextField();
        autoGetAPK = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slot1 = new javax.swing.JRadioButton();
        slot2 = new javax.swing.JRadioButton();
        slot3 = new javax.swing.JRadioButton();
        slot4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        useTablet = new javax.swing.JCheckBox();
        landscapeOrientation = new javax.swing.JRadioButton();
        portraitOrientation = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        apkBox = new javax.swing.JTextField();
        browseAPK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        buildIt = new javax.swing.JButton();

        errorDia.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        errorDia.setTitle("Error!");
        errorDia.setAlwaysOnTop(true);
        errorDia.setResizable(false);

        okError.setText("OK");
        okError.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    okErrorActionPerformed(evt);
                }
            });

        errorText.setText("jLabel7");

        javax.swing.GroupLayout errorDiaLayout = new javax.swing.GroupLayout(errorDia.getContentPane());
        errorDia.getContentPane().setLayout(errorDiaLayout);
        errorDiaLayout.setHorizontalGroup(
            errorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDiaLayout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(okError)
                .addContainerGap())
            .addGroup(errorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errorDiaLayout.setVerticalGroup(
            errorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(okError)
                .addContainerGap())
        );

        writeDir.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        writeDir.setDialogTitle("Save Directory");
        writeDir.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        readAPK.setAcceptAllFileFilterUsed(false);
        readAPK.setDialogTitle("Open APK");
        readAPK.setFileFilter(new FileNameExtensionFilter("APK Archives", "apk"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JARC-APK Extension Builder");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JARC-APK ARC Extension Builder");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buildTarget.add(chromeOSBuild);
        chromeOSBuild.setSelected(true);
        chromeOSBuild.setText("Chrome OS");
        chromeOSBuild.setToolTipText("Builds the application for use on a ChromeBook or on Chrome OS.");

        buildTarget.add(archonBuild);
        archonBuild.setText("Chrome / ARChon");
        archonBuild.setToolTipText("Builds the application for Chrome running ARChon.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chromeOSBuild)
                    .addComponent(archonBuild))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chromeOSBuild)
                .addGap(6, 6, 6)
                .addComponent(archonBuild)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Build Target:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pkgName.setText("Enter a package name");

        autoGetAPK.setSelected(true);
        autoGetAPK.setText("Try to automatically get name");
        autoGetAPK.setToolTipText("Tries to parse the APK in order to get the package name.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoGetAPK)
                    .addComponent(pkgName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pkgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoGetAPK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Package Name:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        slotBG.add(slot1);
        slot1.setSelected(true);
        slot1.setText("Slot 1");
        slot1.setActionCommand("1");

        slotBG.add(slot2);
        slot2.setText("Slot 2");
        slot2.setActionCommand("2");

        slotBG.add(slot3);
        slot3.setText("Slot 3");
        slot3.setActionCommand("3");

        slotBG.add(slot4);
        slot4.setText("Slot 4");
        slot4.setActionCommand("4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slot1)
                    .addComponent(slot2)
                    .addComponent(slot3)
                    .addComponent(slot4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Application to replace (Chrome OS only):");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        useTablet.setText("Tablet Resolution");

        orientationGroup.add(landscapeOrientation);
        landscapeOrientation.setText("Landscape Orientation");

        orientationGroup.add(portraitOrientation);
        portraitOrientation.setSelected(true);
        portraitOrientation.setText("Portrait Orientation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useTablet)
                    .addComponent(landscapeOrientation)
                    .addComponent(portraitOrientation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useTablet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(landscapeOrientation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(portraitOrientation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Additional Options:");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        browseAPK.setText("Browse...");
        browseAPK.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    browseAPKActionPerformed(evt);
                }
            });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apkBox)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(browseAPK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseAPK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("APK:");

        buildIt.setText("Build");
        buildIt.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buildItActionPerformed(evt);
                }
            });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(buildIt)))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buildIt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okErrorActionPerformed
        errorDia.dispose();
    }//GEN-LAST:event_okErrorActionPerformed

    private void buildItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildItActionPerformed
        build();
    }//GEN-LAST:event_buildItActionPerformed

    private void browseAPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseAPKActionPerformed
        int returnVal = readAPK.showOpenDialog(JARCUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            apkBox.setText(readAPK.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseAPKActionPerformed

    private void build(){
        //set up variables
        int key = -1;
        String orientation;
        String pkg = null;
        String formFactor;
        File apk;

        //get key info
        if(archonBuild.isSelected()){
            key = 0;
        }
        else{
            key = Integer.parseInt(((JToggleButton.ToggleButtonModel)slotBG.getSelection()).getActionCommand());
        }

        if(key == -1){
            throwError("No build target was selected!");
            return;
        }
        //get orientation. buttongroups with prechecked buttons help with laziness
        if(landscapeOrientation.isSelected()){
            orientation = "landscape";
        }
        else{
            orientation = "portrait";
        }
        //get tablet checkbox value
        if(useTablet.isSelected()){
            formFactor = "tablet";
        }
        else{
            formFactor = "phone";
        }
        //get apk file
        if(apkBox.getText().isEmpty() || apkBox.getText() == null){
            throwError("No APK selected!");
            return;
        }

        apk = new File(apkBox.getText());
        //try to get package name
        if(autoGetAPK.isSelected()){
            try {
                AndroidApk getPkgName = new AndroidApk(apk);
                pkg = getPkgName.getPackageName();
                if(pkg == null && (pkgName.getText().isEmpty() || pkgName.getText() == null || pkgName.getText().equals("Enter a package name") ) ){
                    throwError("Could not get package name. Please enter it manually. This is the text after the \"?id=\" when you look at the application's url in the play store.");
                    return;
                }
            } catch (IOException ex) {
                throwError("IO Error. Either the apk file doesn't exist, can't be read, or is corrupt.");
                return;
            }
        }
        else{
            if(pkgName.getText().isEmpty() || pkgName.getText() == null || pkgName.getText().equals("Enter a package name") ){
                throwError("Please enter a package name or check \"Try to automatically get name\".");
                return;
            }
            else{
                pkg = pkgName.getText();
            }
        }
        //finally write everything
        int returnVal = writeDir.showSaveDialog(JARCUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            ExtensionGenerator x = new ExtensionGenerator(key,orientation,pkg,formFactor,apk);
            x.generate(writeDir.getSelectedFile());
        }

    }

    /**
     * Displays an error window with the given text
     * @param text The error text to display
     */
    public static void throwError(String text){
        errorText.setText(text);
        if(text.equals("Operation Complete!")){
            errorDia.setTitle("Done!");
        }
        else{
            errorDia.setTitle("Error!");
        }
        errorDia.pack();
        errorDia.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new JARCUI().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apkBox;
    private javax.swing.JRadioButton archonBuild;
    private javax.swing.JCheckBox autoGetAPK;
    private javax.swing.JButton browseAPK;
    private javax.swing.JButton buildIt;
    private javax.swing.ButtonGroup buildTarget;
    private javax.swing.JRadioButton chromeOSBuild;
    private static javax.swing.JDialog errorDia;
    private static javax.swing.JLabel errorText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton landscapeOrientation;
    private javax.swing.JButton okError;
    private javax.swing.ButtonGroup orientationGroup;
    private javax.swing.JTextField pkgName;
    private javax.swing.JRadioButton portraitOrientation;
    private javax.swing.JFileChooser readAPK;
    private javax.swing.JRadioButton slot1;
    private javax.swing.JRadioButton slot2;
    private javax.swing.JRadioButton slot3;
    private javax.swing.JRadioButton slot4;
    private javax.swing.ButtonGroup slotBG;
    private javax.swing.JCheckBox useTablet;
    private javax.swing.JFileChooser writeDir;
    // End of variables declaration//GEN-END:variables
}
