/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jarc.apk;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JToggleButton;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.erdfelt.android.apk.AndroidApk;

/**
 * UI of JARC-APK
 * @author Paul Alves
 */
public class JARCUI extends javax.swing.JFrame {

    private ArrayList<String> files = new ArrayList<>();
    private DefaultListModel<String> fileListModel = new DefaultListModel<>();

    /**
     * Creates new form JARCUI
     */
    public JARCUI() {
        initComponents();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildTarget = new javax.swing.ButtonGroup();
        slotBG = new javax.swing.ButtonGroup();
        orientationGroup = new javax.swing.ButtonGroup();
        errorDia = new javax.swing.JDialog();
        okError = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        writeDir = new javax.swing.JFileChooser();
        readAPK = new javax.swing.JFileChooser();
        addAdditionalFile = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chromeOSBuild = new javax.swing.JRadioButton();
        archonBuild = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pkgName = new javax.swing.JTextField();
        autoGetAPK = new javax.swing.JCheckBox();
        appNameBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slot1 = new javax.swing.JRadioButton();
        slot2 = new javax.swing.JRadioButton();
        slot3 = new javax.swing.JRadioButton();
        slot4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        useTablet = new javax.swing.JCheckBox();
        landscapeOrientation = new javax.swing.JRadioButton();
        portraitOrientation = new javax.swing.JRadioButton();
        enableAdb = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        apkBox = new javax.swing.JTextField();
        browseAPK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filesList = new javax.swing.JList();
        addFile = new javax.swing.JButton();
        delFile = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buildIt = new javax.swing.JButton();

        errorDia.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        errorDia.setTitle("Error!");
        errorDia.setAlwaysOnTop(true);
        errorDia.setResizable(false);

        okError.setText("OK");
        okError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okErrorActionPerformed(evt);
            }
        });

        errorText.setText("jLabel7");

        javax.swing.GroupLayout errorDiaLayout = new javax.swing.GroupLayout(errorDia.getContentPane());
        errorDia.getContentPane().setLayout(errorDiaLayout);
        errorDiaLayout.setHorizontalGroup(
            errorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDiaLayout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(okError)
                .addContainerGap())
            .addGroup(errorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errorDiaLayout.setVerticalGroup(
            errorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(okError)
                .addContainerGap())
        );

        writeDir.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        writeDir.setDialogTitle("Save Directory");
        writeDir.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        readAPK.setAcceptAllFileFilterUsed(false);
        readAPK.setDialogTitle("Open APK");
        readAPK.setFileFilter(new FileNameExtensionFilter("APK Archives", "apk"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JARC-APK Extension Builder");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JARC-APK ARC Extension Builder");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buildTarget.add(chromeOSBuild);
        chromeOSBuild.setText("Chrome OS (Version 37 or earlier)");
        chromeOSBuild.setToolTipText("Builds the application for use on a ChromeBook or on Chrome OS older than version 38.");

        buildTarget.add(archonBuild);
        archonBuild.setSelected(true);
        archonBuild.setText("Chrome / ARChon / Chrome OS");
        archonBuild.setToolTipText("Builds the application for Chrome running ARChon or Chrome OS running later than version 37.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chromeOSBuild)
                    .addComponent(archonBuild))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chromeOSBuild)
                .addGap(6, 6, 6)
                .addComponent(archonBuild)
                .addGap(28, 28, 28))
        );

        jLabel2.setText("Build Target:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pkgName.setText("Enter a package name");

        autoGetAPK.setSelected(true);
        autoGetAPK.setText("Try to automatically get package name");
        autoGetAPK.setToolTipText("Tries to parse the APK in order to get the package name.");

        appNameBox.setText("Enter an app name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autoGetAPK)
                    .addComponent(pkgName)
                    .addComponent(appNameBox))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pkgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoGetAPK)
                .addGap(18, 18, 18)
                .addComponent(appNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Package / App Name:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        slotBG.add(slot1);
        slot1.setSelected(true);
        slot1.setText("Slot 1");
        slot1.setActionCommand("1");

        slotBG.add(slot2);
        slot2.setText("Slot 2");
        slot2.setActionCommand("2");

        slotBG.add(slot3);
        slot3.setText("Slot 3");
        slot3.setActionCommand("3");

        slotBG.add(slot4);
        slot4.setText("Slot 4");
        slot4.setActionCommand("4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slot1)
                    .addComponent(slot2)
                    .addComponent(slot3)
                    .addComponent(slot4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Application to replace (Chrome OS only):");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        useTablet.setText("Tablet Resolution");

        orientationGroup.add(landscapeOrientation);
        landscapeOrientation.setText("Landscape Orientation");

        orientationGroup.add(portraitOrientation);
        portraitOrientation.setSelected(true);
        portraitOrientation.setText("Portrait Orientation");

        enableAdb.setText("Enable ADB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useTablet)
                    .addComponent(enableAdb)
                    .addComponent(landscapeOrientation)
                    .addComponent(portraitOrientation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useTablet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enableAdb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(landscapeOrientation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(portraitOrientation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Additional Options:");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        browseAPK.setText("Browse...");
        browseAPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseAPKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apkBox)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(browseAPK)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseAPK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("APK:");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        filesList.setModel(getListModel());
        filesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(filesList);

        addFile.setText("Add");
        addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileActionPerformed(evt);
            }
        });

        delFile.setText("Delete");
        delFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delFile)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setText("Additional Files:");

        buildIt.setText("Build");
        buildIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildItActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(buildIt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildIt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okErrorActionPerformed
        errorDia.dispose();
    }//GEN-LAST:event_okErrorActionPerformed

    private void buildItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildItActionPerformed
        build();
    }//GEN-LAST:event_buildItActionPerformed

    private ListModel getListModel(){
    return fileListModel;
    }
    
    private void browseAPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseAPKActionPerformed
        int returnVal = readAPK.showOpenDialog(JARCUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            apkBox.setText(readAPK.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseAPKActionPerformed

    private void addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileActionPerformed
        int returnVal = addAdditionalFile.showOpenDialog(JARCUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            files.add(addAdditionalFile.getSelectedFile().getAbsolutePath());
            fileListModel.addElement(addAdditionalFile.getSelectedFile().getAbsolutePath());
            filesList.setModel(fileListModel);
        }
    }//GEN-LAST:event_addFileActionPerformed

    private void delFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delFileActionPerformed
        int index = filesList.getSelectedIndex();
        if(index < 0){return;}
        files.remove(index);
        fileListModel.removeElementAt(index);
    }//GEN-LAST:event_delFileActionPerformed

    private void build(){
        //set up variables
        int key = -1;
        String orientation;
        String pkg = null;
        String formFactor;
        File apk;

        //get key info
        if(archonBuild.isSelected()){
            key = 0;
        }
        else{
            key = Integer.parseInt(((JToggleButton.ToggleButtonModel)slotBG.getSelection()).getActionCommand());
        }

        if(key == -1){
            throwError("No build target was selected!");
            return;
        }
        //get orientation. buttongroups with prechecked buttons help with laziness
        if(landscapeOrientation.isSelected()){
            orientation = "landscape";
        }
        else{
            orientation = "portrait";
        }
        //get tablet checkbox value
        if(useTablet.isSelected()){
            formFactor = "tablet";
        }
        else{
            formFactor = "phone";
        }
        //get apk file
        if(apkBox.getText().isEmpty() || apkBox.getText() == null){
            throwError("No APK selected!");
            return;
        }

        apk = new File(apkBox.getText());
        //try to get package name
        if(autoGetAPK.isSelected()){
            try {
                AndroidApk getPkgName = new AndroidApk(apk);
                pkg = getPkgName.getPackageName();
                if(pkg == null && (pkgName.getText().isEmpty() || pkgName.getText() == null || pkgName.getText().equals("Enter a package name") ) ){
                    throwError("Could not get package name. Please enter it manually. This is the text after the \"?id=\" when you look at the application's url in the play store.");
                    return;
                }
            } catch (IOException ex) {
                throwError("IO Error. Either the apk file doesn't exist, can't be read, or is corrupt.");
                return;
            }
        }
        else{
            if(pkgName.getText().isEmpty() || pkgName.getText().equals("Enter a package name") ){
                throwError("Please enter a package name or check \"Try to automatically get name\".");
                return;
            }
            else{
                pkg = pkgName.getText();
            }
        }
        boolean adb = enableAdb.isSelected();
        String appName = appNameBox.getText();
        if(appName.isEmpty() || appName.equals("Enter an app name")){
            appName = "Unnamed App";
        }
        //finally write everything
        int returnVal = writeDir.showSaveDialog(JARCUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            ExtensionGenerator x = new ExtensionGenerator(key,orientation,pkg,formFactor,apk,adb,appName);
            x.generate(writeDir.getSelectedFile());
            String sep = ExtensionGenerator.sep;
            File dumpFiles = new File(writeDir.getSelectedFile() + sep + pkg + sep + "vendor" + sep + "chromium" + sep + "crx" + sep);
            if(!dumpFiles.exists() || files.isEmpty()){
                return;
            }

            InputStream inStream = null; 
            OutputStream outStream = null; 
            for(String s : files)
            {
                try{ 
                    File oFile = new File(s);
                    File f = new File(dumpFiles.getAbsolutePath() + sep +  oFile.getName());
                    inStream = new FileInputStream(oFile); 
                    outStream = new FileOutputStream(f); 
                    byte[] buffer = new byte[1024]; 
                    int length; 
                    while ((length = inStream.read(buffer)) > 0){ 
                        outStream.write(buffer, 0, length); 
                    } 
                    inStream.close(); 
                    outStream.close(); 
                }catch(IOException e){ 
                    throwError("Could not copy one or more additional files. Please check that they exist and you have access to them.");
                } 
            }
        }

    }

    /**
     * Displays an error window with the given text
     * @param text The error text to display
     */
    public static void throwError(String text){
        
        //this is probably a very horrible way to do this...
        
        if(errorText == null){System.out.println(text);return;}
        
        errorText.setText(text);
        if(text.equals("Operation Complete!")){
            errorDia.setTitle("Done!");
        }
        else{
            errorDia.setTitle("Error!");
        }
        errorDia.pack();
        errorDia.setLocationRelativeTo(null); //center ze window
        errorDia.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        if(args.length >= 4)
        {
            System.out.println("JARC-APK v1.3\ngummywormz.github.io");
            
            String input = null;
            String output = null;
            boolean enableAdb = false;
            String form = null;
            String orientation = null;
            String appname = null;
            String pkg = null;
            int key = 0;
            for(int i = 0; i < args.length; i++)
            {
                if(args[i].equals("-i")){input = args[i+1];}
                if(args[i].equals("-o")){output = args[i+1];}
                if(args[i].equals("-n")){appname = args[i+1];}
                if(args[i].equals("-e")){enableAdb = true;}
                if(args[i].equals("-f")){form = args[i+1];}
                if(args[i].equals("-r")){orientation = args[i+1];}
                if(args[i].equals("-k")){key = Integer.parseInt(args[i+1]);}
            }
            
            if (input == null || output == null){System.out.println("Input or output not specified"); System.exit(1);}
            if (form == null){form = "phone";}
            if (orientation == null){orientation = "portrait";}

            
            AndroidApk a;
            try {
                a = new AndroidApk(new File(input));
                pkg = a.getPackageName();
            } catch (IOException ex) {
                System.out.println("Invalid Apk"); 
                System.exit(1);
            }
            
            if (appname == null){appname = pkg;}
            
            
            ExtensionGenerator x = new ExtensionGenerator(key,orientation,pkg,form,new File(input),enableAdb,appname);
            File f = new File(output);
            x.generate(f);
            System.exit(0);
        
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JARCUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new JARCUI().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser addAdditionalFile;
    private javax.swing.JButton addFile;
    private javax.swing.JTextField apkBox;
    private javax.swing.JTextField appNameBox;
    private javax.swing.JRadioButton archonBuild;
    private javax.swing.JCheckBox autoGetAPK;
    private javax.swing.JButton browseAPK;
    private javax.swing.JButton buildIt;
    private javax.swing.ButtonGroup buildTarget;
    private javax.swing.JRadioButton chromeOSBuild;
    private javax.swing.JButton delFile;
    private javax.swing.JCheckBox enableAdb;
    private static javax.swing.JDialog errorDia;
    private static javax.swing.JLabel errorText;
    private javax.swing.JList filesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton landscapeOrientation;
    private javax.swing.JButton okError;
    private javax.swing.ButtonGroup orientationGroup;
    private javax.swing.JTextField pkgName;
    private javax.swing.JRadioButton portraitOrientation;
    private javax.swing.JFileChooser readAPK;
    private javax.swing.JRadioButton slot1;
    private javax.swing.JRadioButton slot2;
    private javax.swing.JRadioButton slot3;
    private javax.swing.JRadioButton slot4;
    private javax.swing.ButtonGroup slotBG;
    private javax.swing.JCheckBox useTablet;
    private javax.swing.JFileChooser writeDir;
    // End of variables declaration//GEN-END:variables
}
